Repository chandantiwari1/students-portal, pull requests merged in 2022-10, with the labels that each got.

#10 Dev
  CONTRIBUTORS.md
  CONTRIBUTORS/Shivam_Pandey.md
  package-lock.json
  package.json
Labels: hacktoberfest-accepted

#14 Added profile
  CONTRIBUTORS.md
Labels: hacktoberfest

#16 created merge.cpp
  merge.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#42 added code to print a heart pattern in C language
  heart.cpp
  heart.exe
Labels: hacktoberfest

#51 Create caesar_cipher.py
  caesar_cipher.py
Labels: hacktoberfest, hacktoberfest-accepted

#50 Radix program added
  DMA.c
  FibonacciSeries.c
  RadixSort.c
  socket/package.json
Labels: hacktoberfest, hacktoberfest-accepted

#55 selection sort algorithm
  selection sort algorithm
Labels: hacktoberfest-accepted

#54 javascript engine
  javascript engine
Labels: hacktoberfest-accepted

#53 program to fetch date and time from web api
  program to fetch date and time from web api
Labels: hacktoberfest-accepted

#52 fibonacci series
  fibonacci series
Labels: hacktoberfest-accepted

#47 Dev4
  CPP/Selectionsort.cpp
  CPP/heart.cpp
  CPP/merge.cpp
Labels: hacktoberfest-accepted

#43 added folder structure
  README.md
Labels: hacktoberfest-accepted

#62 oddevenn.py
  oddevenn.py
Labels: hacktoberfest, hacktoberfest-accepted

#64 fabonacciseriess.py
  fabonacciseriess.py
Labels: hacktoberfest, hacktoberfest-accepted

#63 maxofthree.py
  maxofthree.py
Labels: hacktoberfest, hacktoberfest-accepted
